version: '3'

services:
  baidu-autosave:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baidu-autosave
    restart: unless-stopped
    ports:
      - "5001:5000"
    volumes:
      - ./config:/app/config
      - ./log:/app/log
    environment:
      - TZ=Asia/Shanghai